---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: stemcell-builder
  - name: base-gcp-image
    path: stemcell-builder/build/base-gcp-image
  - name: compiled-agent
    path: stemcell-builder/build/compiled-agent
  - name: version
    path: stemcell-builder/build/version
  - name: windows-stemcell-dependencies
    path: stemcell-builder/build/windows-stemcell-dependencies

outputs:
  - name: bosh-windows-stemcell

run:
  path: stemcell-builder/scripts/create-gcp-stemcell.rb

params:
  OUTPUT_DIR:
  OS_VERSION: windows2012R2
  ACCOUNT_JSON:
