---
platform: windows

inputs:
  - name: vmx-version
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION: us-east-1

  ADMINISTRATOR_PASSWORD: replace-me

  INPUT_BUCKET: "bosh-windows-stemcell-vmx"
  VMX_CACHE: "C:\\vmx-data"

run:
  path: ruby.exe
  args:
    - stemcell-builder/scripts/create-vmx-add-updates.rb
