---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: stemcell-regions
  - name: compiled-agent
  - name: version
  - name: stemcell-builder

outputs:
  - name: bosh-windows-stemcell
  - name: amis

run:
  path: stemcell-builder/scripts/create-aws-stemcell.rb

params:
  OUTPUT_DIR:
  OS_VERSION: windows2012R2
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

