---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: version
  - name: compiled-agent
  - name: vsphere-stemcell-vmx
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
outputs:
  - name: bosh-windows-stemcell

params:
  ADMINISTRATOR_PASSWORD: replace-me
run:
  path: stemcell-builder/scripts/create-vmx-stemcell.rb
