----
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
	- name: stemcell-builder

run:
  path: bash
  args:
   - -ex
   - |
    cd stemcell-builder
    bundle install
    bundle exec rspec
